builds:
  - main: ./pinger.go
    binary: pinger
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
# Archive customization
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    amd64: x64
    darwin: mac
  files:
    - README.md
    - LICENSE
changelog:
  filters:
    exclude:
      - '^!clog:'